language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - 'nightly'

env:
  - COMPOSER_FLAGS=
  - COMPOSER_FLAGS=--prefer-lowest

matrix:
  allow_failures:
    - php: 'nightly'

before_script:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry phpenv rehash

install:
  - composer update $COMPOSER_FLAGS --no-interaction --prefer-dist --no-progress --no-suggest --ansi

script:
  - ./vendor/bin/phpcs --standard=psr2 -n src/
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v
