<?php

namespace BenTools\Shh;

use Symfony\Component\HttpKernel\Bundle\Bundle;

final class ShhBundle extends Bundle
{
    public function getContainerExtension()
    {
        return parent::getContainerExtension(); // TODO: Change the autogenerated stub
    }
}
